language: go

go: 1.8

branches:
  except:
    - /^*-[0-9]/

install:
  - make install

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - |
    if [ -z "$TRAVIS_TAG" ]; then
      echo "Using TRAVIS_BUILD_NUMBER as revision..."
      export CLI_VERSION="${CLI_FEATURE_VERSION}.${TRAVIS_BUILD_NUMBER}";
    else
      echo "Using TRAVIS_TAG as revision..."
      export CLI_VERSION="${TRAVIS_TAG}"
    fi
  - TARGET_PLATFORM=darwin make release
  - TARGET_PLATFORM=linux make release

env:
  global:
    - CLI_FEATURE_VERSION=0.9
    - CLI_VERSION="${CLI_FEATURE_VERSION}.${TRAVIS_BUILD_NUMBER}"
    - secure: "QmuvdaTwMS0A6VLjgVFPRc+tqi8wru91qhrWf9wQK1QLvvh7yGQvnJiMjIl1gumVHfRxniGrDEJMBd8ff2ems5N41YXer9iU/+F4n5q4ySLTIH+UW6bBfWTS+vQUJijPVId5zsKglJS91loeIazfzBjwICjFsTxYhBVoXrEk9r7iVksKJGHR2Iabuz4nj7nvRohB5cbyxL+J9Txa0QAjWxlqUWQRTnsRomROBtwX9POFgHvcalqpsaokR9FnWB0+TDn0FKloYNyoyIHzoqL+XHm8VYOkkgE2CWHlpPOZw0pdOlitd0Gf/rqYZTSGqTkl+0tab/InmpCTldI97Jx4lz92vTJkUbzcpa2f4ZLJAVnJELnFAePMzJ6Dfy3SrS6gp/g/0AfbmY9VXFSBFyvjxNfOdgbzkswRK0W2xbCCLHrCA8jVZVzK+ptxTJdqkX3InggSaxEo0Z4fkeIapAYB/Cwx8O38+Hj8HzYrZNefYLU0QtrS+LJobQfG8goF9+B0tBEn381OI9jecFRfG1y1VafwYGkj7pNiTi2UEGakFuvpSf0aWUsRFxi7VCyy1V1ElejBaqbqmrr1MBfHaLT0j0wwI5RInTtOtZBABAmfHtEHWIXxsar27e004EICSN8zAHvNjfa5FAa9lZoFyS/wi6cdsYMfMzUsEs9WjMkm7HE="

# if this isnt a PR, and we're building the master branch *only*, then lets tag
# this version which will in turn trigger another build that the github release
# will be cut from.
after_success:
- |
  if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    if [ $TRAVIS_BRANCH = 'master' ]; then
      git config --global user.email "builds@travis-ci.com"
      git config --global user.name "Travis CI"
      git tag ${CLI_VERSION} -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
      git push -q https://$GIT_CREDENTIAL@github.com/Verizon/slipway --tags
    fi
  fi

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: target/*
  api_key:
    secure: EhCYGwNLvp0OXly/LixObDrKn3mlUBm2+xjcfJ5EUXGJ7OfSplYg32KRsNH46Mk9AZBoVMsGBBoW0+TDun1op8ex0D3Vo+xF/umW6WLlLZIgmehj2rvFICQznwSckXfyRD6O4V0m1ieS/lUSdTNPfKCETw6/iupa/D5nIhnR/3CjqrMBod/LOVMspet3PmM53q4b1CLOG6P3g3n6JmfEhO6qk5KlsqAOalJ7sS+4WjgDutYnN8Hll/cBa0mk/fAuqk02DuxVMRm24/5Dz/HlIjh8Gme2+FanFLEITcm+8V0cmS+CZ0JFyN1zosqh7MclHsN8fhjfHjAc1j4YbRJo9AWhPLfqF9Ak/Rdwtf3fjPiHIIzv8/vxQqGZt2kUp/QM9z3CVU8XatUCB7iZEZWjwvQ4zHTZ2ZWBxUsJAGmp46Enyb7+HZx+Y2Rxichu2cmifcJAhhXTh2CVU5JJcSyP8FaZIeU9BH5f6+9J6eDkTBB/RE3YrCyCIxCSgyjm662SsUCURr09+/xytXLG8xlrGxnPzwCBekRo8pnbadDujEa3cjKwgzzPm4NoLNjZcGr527biXmGzbTQlZzNHdqaYcL4MAuFGo/35Ceq+GVvQavmltQG/ds3c9pjcW+ry2RpyFRCq5bloLtNysyk7kgBXTc9enMeS+aCjHhDA8HzYo+M=
  on:
    tags: true
    repo: Verizon/nelson-cli
